name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Run Tests
        run: ./tests/run.sh
