name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Get Luver Downloads Cache Key
        id: luver-downloads-cache-key
        env:
          CI_RUNNER_OS: ${{ runner.os }}
        run: |
          echo "::set-output name=value::${CI_RUNNER_OS}-$(date -u +%Y-%m-%d)"
        shell: bash
      - name: Setup Luver Downloads Cache
        id: luver-downloads-cache
        uses: actions/cache@v2
        with:
          path: tests/.temp/home/.local/share/luver/.downloads
          key: ${{ steps.luver-downloads-cache-key.outputs.value }}
      - name: Run Tests
        run: ./tests/run.sh
